{
 "title": "HTTP请求状态统计",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HTTP SUCCESS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP POST/200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"200\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "HTTP PUT/200",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"200\",method=\"PUT\"}"
    }
   ]
  },
  {
   "title": "HTTP GET/200",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"200\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "HTTP ERROR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP GET/200",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status!=\"200\"}"
      }
     ]
    }
   ]
  }
 ]
}