{
 "title": "汇总统计",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "订单 (根据所选时间变化，建议不要选择超过1个月）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "已发货 - 订单总金额",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  productPrice * count(orderId) AS \"Total\"\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and STATUS='DELIVERED'\nORDER BY createTime"
    }
   ]
  },
  {
   "title": "商品已付款 - 总金额",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  productPrice * count(orderId) AS \"Total\"\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and STATUS='PAY_PRODUCT_SUCCESS'\nORDER BY createTime"
    }
   ]
  },
  {
   "title": "运费已付 - 总金额",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  productPrice * count(orderId) AS \"Total\"\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and STATUS='PAY_TRANSPORT_SUCCESS'\nORDER BY createTime"
    }
   ]
  },
  {
   "title": "产品付款超时/失败次数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(orderId) AS \"count\"\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and (STATUS='PAY_PRODUCT_FAIL' or STATUS='PAY_PRODUCT_EXPIRY')\nORDER BY createTime"
    }
   ]
  },
  {
   "title": "运费超时/失败次数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(orderId) AS \"count\"\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and (STATUS='PAY_TRANSPORT_EXPIRY' or STATUS='PAY_TRANSPORT_FAIL')\nORDER BY createTime"
    }
   ]
  },
  {
   "title": "已发货订单",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  createTime AS \"time\",\n  productName AS \"ProductName\",\n  productPrice AS \"Price\",\n  count(orderId) AS \"SoldNumber\",\n  productPrice * count(orderId) AS \"Total\"\n\nFROM order_tbl\nWHERE\n  $__timeFilter(createTime) and STATUS='DELIVERED'\nGROUP BY productName\nORDER BY createTime"
    }
   ]
  },
  { "title": "用户", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "用户总数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select count(open_id) from wx_user_tbl;"
    }
   ]
  },
  {
   "title": "用户积分前20名",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "rawSql": "select open_id,nick_name,bonus from wx_user_tbl order by bonus desc limit 20;"
    }
   ]
  },
  {
   "title": "HTTP SUCCESS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP POST/200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=\"200\",method=\"POST\"}"
      }
     ]
    },
    {
     "title": "HTTP PUT/200",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=\"200\",method=\"PUT\"}"
      }
     ]
    },
    {
     "title": "HTTP GET/200",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=\"200\",method=\"GET\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP ERROR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP GET/200",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status!=\"200\"}"
      }
     ]
    }
   ]
  }
 ]
}