spring:
  application:
    name: blindbox
  datasource:
    url: jdbc:h2:mem:RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

management:
  endpoints:
    health:
      show-details: 'always'
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}



#can remove if using jdbc
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

swagger:
  enable: true

app:
  appId: "wx7bd98b0c17d22c3e"
  appSecret: "ec92fc66664da96895b4e96cfb2e5a13"
  mchId: "1586641511"
  mchSecret: "Udol1029384756102938475610293847"
  imagePath: "/opt/apps/blindbox"