spring:
  datasource:
    url: jdbc:h2:mem:RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL

#can remove if using jdbc
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

swagger:
  enable: true

app:
  appId: "wx7bd98b0c17d22c3e"
  appSecret: "ec92fc66664da96895b4e96cfb2e5a13"
  imagePath: "./blindbox"