package com.github.tuding.blindbox.exception;

public enum ErrorCode {

    // Wxchat related
    FAIL_TO_GET_OPENID,
    FAIL_TO_GET_WXCHAT_ACCESS_TOKEN,
    INVALID_AES_KEY,
    INVALID_IV,
    ILLEGAL_BUFFER,
    FAIL_TO_DECRYPT,
    FAIL_TO_PLACE_ORDER_TO_WX,
    INVALID_SIGN,

    //User
    FAIL_TO_UPDATE_USER_INFO,
    WX_USER_NOT_FOUND,
    FAIL_TO_MODIFY_SHIPPING_ADDRESS,
    BONUS_NOT_ENOUGH,
    FAIL_TO_UPDATE_BONUS,
    TRANSPORT_AREA_NOT_SUPPORT,

    //Infra
    FAIL_TO_STORE_FILE,

    //Activity
    INVALID_ACTIVITY_ID,
    SHOULD_NOT_REG_NOTIFY_FOR_ACTIVITY_WHEN_STARTED,
    NOTIFY_REDIRECT_PAGE_SHOULD_NOT_BE_NULL_OR_EMPTY,

    //Product
    FAIL_TO_GET_PRICE_BY_DRAWID,
    DRAWID_NOT_FOUND,

    //Order
    INVALID_STATUS,
}
