create TABLE barrage_tbl (
  nick_name varchar(255),
  PRIMARY KEY (nick_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into barrage_tbl (nick_name) values ('Nate·昊');
insert into barrage_tbl (nick_name) values ('gcdeybb');
insert into barrage_tbl (nick_name) values ('Martin');
insert into barrage_tbl (nick_name) values ('ROCK嘉');
insert into barrage_tbl (nick_name) values ('欧阳慧敏');
insert into barrage_tbl (nick_name) values ('李心阳');
insert into barrage_tbl (nick_name) values ('司宏玺');
insert into barrage_tbl (nick_name) values ('漫步云端');
insert into barrage_tbl (nick_name) values ('Bin寶');
insert into barrage_tbl (nick_name) values ('零号 ');
insert into barrage_tbl (nick_name) values ('Yuan');
insert into barrage_tbl (nick_name) values ('韩大江');
insert into barrage_tbl (nick_name) values ('GSJ');
insert into barrage_tbl (nick_name) values ('Yvonne');
insert into barrage_tbl (nick_name) values ('旺达有为');
insert into barrage_tbl (nick_name) values ('青青体育-管大山');
insert into barrage_tbl (nick_name) values ('早晚进pku');
insert into barrage_tbl (nick_name) values ('李政旭-）');
insert into barrage_tbl (nick_name) values ('F杨帆Y木易巾凡');
insert into barrage_tbl (nick_name) values ('范宪维 ');
insert into barrage_tbl (nick_name) values ('丸子轮');
insert into barrage_tbl (nick_name) values ('QQ娴');
insert into barrage_tbl (nick_name) values ('郭');
insert into barrage_tbl (nick_name) values ('MRayyy.37_');
insert into barrage_tbl (nick_name) values ('半场起跳720°暴扣');
insert into barrage_tbl (nick_name) values ('Cyz_11');
insert into barrage_tbl (nick_name) values ('Shelby.oyc');
insert into barrage_tbl (nick_name) values ('崔东亮');
insert into barrage_tbl (nick_name) values ('陈小小');
insert into barrage_tbl (nick_name) values ('爽Leo');
insert into barrage_tbl (nick_name) values ('Riccchb');
insert into barrage_tbl (nick_name) values ('十点差三分');
insert into barrage_tbl (nick_name) values ('KaChung');
insert into barrage_tbl (nick_name) values ('xyzzz');
insert into barrage_tbl (nick_name) values ('Dream.');
insert into barrage_tbl (nick_name) values ('y余裕。');
insert into barrage_tbl (nick_name) values ('方超巨');
insert into barrage_tbl (nick_name) values ('肖泽云');
insert into barrage_tbl (nick_name) values ('Coco');
insert into barrage_tbl (nick_name) values ('curnin');
insert into barrage_tbl (nick_name) values ('KING . karry');
insert into barrage_tbl (nick_name) values ('Warriors');
insert into barrage_tbl (nick_name) values ('英雄気質MARBAS');
insert into barrage_tbl (nick_name) values ('张浩宇');
insert into barrage_tbl (nick_name) values ('stoney');
insert into barrage_tbl (nick_name) values ('林思跃');
insert into barrage_tbl (nick_name) values ('苏文涛');
insert into barrage_tbl (nick_name) values ('Lxiao薇.');
insert into barrage_tbl (nick_name) values ('阿郭呦');
insert into barrage_tbl (nick_name) values ('阮程');
insert into barrage_tbl (nick_name) values ('王隽喆');
insert into barrage_tbl (nick_name) values ('ㅤ又一個夏天');
insert into barrage_tbl (nick_name) values ('憨厚的涛涛');
insert into barrage_tbl (nick_name) values ('77');
insert into barrage_tbl (nick_name) values ('关于篮球');
insert into barrage_tbl (nick_name) values ('Rrrrr.');
insert into barrage_tbl (nick_name) values ('v');
insert into barrage_tbl (nick_name) values ('G-G Bond° ');
insert into barrage_tbl (nick_name) values ('彭伟权');
insert into barrage_tbl (nick_name) values ('Sol_ ');
insert into barrage_tbl (nick_name) values ('W.A.N');
insert into barrage_tbl (nick_name) values ('Terry.');
insert into barrage_tbl (nick_name) values ('venom');
insert into barrage_tbl (nick_name) values ('GT');
insert into barrage_tbl (nick_name) values ('magical');
insert into barrage_tbl (nick_name) values ('保持恒温。');
insert into barrage_tbl (nick_name) values ('小鹿拽森');
insert into barrage_tbl (nick_name) values ('Lynn丽颖');
insert into barrage_tbl (nick_name) values ('6号没睡醒啊');
insert into barrage_tbl (nick_name) values ('鸣镝');